"""match prematch features

Revision ID: 6ae97aaffe36
Revises: 77a8cbdb6a08
Create Date: 2026-08-27 06:59:22.225162
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6ae97aaffe36'
down_revision: str | None = '77a8cbdb6a08'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_prematch',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prematch_prior', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_prematch_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_match_prematch'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_prematch')
    # ### end Alembic commands ###
