"""initial schema

Revision ID: 6c1b498f1c83
Revises: 
Create Date: 2026-08-26 12:46:03.998846
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6c1b498f1c83'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_checkpoints',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('cursor', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_ingest_checkpoints'))
    )
    op.create_table('leagues',
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('liquipedia_slug', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('is_lan', sa.Boolean(), nullable=True),
    sa.Column('prize_pool', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_leagues'))
    )
    op.create_index(op.f('ix_leagues_liquipedia_slug'), 'leagues', ['liquipedia_slug'], unique=False)
    op.create_table('player_ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_match_id', sa.BigInteger(), nullable=True),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_ratings'))
    )
    op.create_index('ix_player_ratings_account_time', 'player_ratings', ['account_id', 'as_of_time'], unique=False)
    op.create_table('players',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('fantasy_role', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_players'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('p_radiant', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('ix_predictions_match_minute', 'predictions', ['match_id', 'minute'], unique=False)
    op.create_table('raw_liquipedia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_liquipedia'))
    )
    op.create_index(op.f('ix_raw_liquipedia_slug'), 'raw_liquipedia', ['slug'], unique=False)
    op.create_table('raw_live_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('server_steam_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_live_snapshots'))
    )
    op.create_index('ix_raw_live_snapshots_match_captured', 'raw_live_snapshots', ['match_id', 'captured_at'], unique=False)
    op.create_table('raw_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_matches')),
    sa.UniqueConstraint('match_id', 'source', name='uq_raw_matches_match_source')
    )
    op.create_index(op.f('ix_raw_matches_match_id'), 'raw_matches', ['match_id'], unique=False)
    op.create_table('team_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_features'))
    )
    op.create_index('ix_team_features_team_time', 'team_features', ['team_id', 'as_of_time'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_teams'))
    )
    op.create_table('team_rosters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_standin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['players.account_id'], name=op.f('fk_team_rosters_account_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name=op.f('fk_team_rosters_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_rosters'))
    )
    op.create_index(op.f('ix_team_rosters_account_id'), 'team_rosters', ['account_id'], unique=False)
    op.create_index(op.f('ix_team_rosters_team_id'), 'team_rosters', ['team_id'], unique=False)
    op.create_table('tournament_stages',
    sa.Column('stage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_type', sa.String(length=16), nullable=False),
    sa.Column('default_format', sa.String(length=8), nullable=False),
    sa.Column('points_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('liquipedia_slug', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name=op.f('fk_tournament_stages_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_id', name=op.f('pk_tournament_stages'))
    )
    op.create_index(op.f('ix_tournament_stages_league_id'), 'tournament_stages', ['league_id'], unique=False)
    op.create_table('series',
    sa.Column('series_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('stage_id', sa.BigInteger(), nullable=True),
    sa.Column('team_a_id', sa.BigInteger(), nullable=True),
    sa.Column('team_b_id', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.BigInteger(), nullable=True),
    sa.Column('is_draw', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valve_series_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (is_draw AND winner_team_id IS NOT NULL)', name=op.f('ck_series_draw_has_no_winner')),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name=op.f('fk_series_league_id_leagues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stages.stage_id'], name=op.f('fk_series_stage_id_tournament_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.team_id'], name=op.f('fk_series_team_a_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.team_id'], name=op.f('fk_series_team_b_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('series_id', name=op.f('pk_series'))
    )
    op.create_index(op.f('ix_series_league_id'), 'series', ['league_id'], unique=False)
    op.create_index(op.f('ix_series_stage_id'), 'series', ['stage_id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('series_id', sa.BigInteger(), nullable=True),
    sa.Column('game_in_series', sa.Integer(), nullable=True),
    sa.Column('is_conditional_game', sa.Boolean(), nullable=False),
    sa.Column('radiant_team_id', sa.BigInteger(), nullable=True),
    sa.Column('dire_team_id', sa.BigInteger(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name=op.f('fk_matches_league_id_leagues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], name=op.f('fk_matches_series_id_series'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_dire_team_id'), 'matches', ['dire_team_id'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_index('ix_matches_league_start', 'matches', ['league_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_matches_radiant_team_id'), 'matches', ['radiant_team_id'], unique=False)
    op.create_index(op.f('ix_matches_series_id'), 'matches', ['series_id'], unique=False)
    op.create_index(op.f('ix_matches_start_time'), 'matches', ['start_time'], unique=False)
    op.create_table('match_drafts',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_pick', sa.Boolean(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_drafts_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'order', name=op.f('pk_match_drafts'))
    )
    op.create_table('match_objectives',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_objectives_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_objectives'))
    )
    op.create_index('ix_match_objectives_match_time', 'match_objectives', ['match_id', 'time'], unique=False)
    op.create_table('match_players',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_slot', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('is_radiant', sa.Boolean(), nullable=False),
    sa.Column('lane_role', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('last_hits', sa.Integer(), nullable=True),
    sa.Column('denies', sa.Integer(), nullable=True),
    sa.Column('net_worth', sa.Integer(), nullable=True),
    sa.Column('gold_per_min', sa.Integer(), nullable=True),
    sa.Column('xp_per_min', sa.Integer(), nullable=True),
    sa.Column('leaver_status', sa.Integer(), nullable=True),
    sa.Column('is_standin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_players_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'player_slot', name=op.f('pk_match_players'))
    )
    op.create_index(op.f('ix_match_players_account_id'), 'match_players', ['account_id'], unique=False)
    op.create_table('match_snapshots',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('radiant_win', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_snapshots_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'minute', name=op.f('pk_match_snapshots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_snapshots')
    op.drop_index(op.f('ix_match_players_account_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index('ix_match_objectives_match_time', table_name='match_objectives')
    op.drop_table('match_objectives')
    op.drop_table('match_drafts')
    op.drop_index(op.f('ix_matches_start_time'), table_name='matches')
    op.drop_index(op.f('ix_matches_series_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_radiant_team_id'), table_name='matches')
    op.drop_index('ix_matches_league_start', table_name='matches')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_dire_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_series_stage_id'), table_name='series')
    op.drop_index(op.f('ix_series_league_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_tournament_stages_league_id'), table_name='tournament_stages')
    op.drop_table('tournament_stages')
    op.drop_index(op.f('ix_team_rosters_team_id'), table_name='team_rosters')
    op.drop_index(op.f('ix_team_rosters_account_id'), table_name='team_rosters')
    op.drop_table('team_rosters')
    op.drop_table('teams')
    op.drop_index('ix_team_features_team_time', table_name='team_features')
    op.drop_table('team_features')
    op.drop_index(op.f('ix_raw_matches_match_id'), table_name='raw_matches')
    op.drop_table('raw_matches')
    op.drop_index('ix_raw_live_snapshots_match_captured', table_name='raw_live_snapshots')
    op.drop_table('raw_live_snapshots')
    op.drop_index(op.f('ix_raw_liquipedia_slug'), table_name='raw_liquipedia')
    op.drop_table('raw_liquipedia')
    op.drop_index('ix_predictions_match_minute', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('players')
    op.drop_index('ix_player_ratings_account_time', table_name='player_ratings')
    op.drop_table('player_ratings')
    op.drop_index(op.f('ix_leagues_liquipedia_slug'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('ingest_checkpoints')
    # ### end Alembic commands ###
