"""unique stage per league

Revision ID: 77a8cbdb6a08
Revises: c9b584045ca2
Create Date: 2026-08-27 05:04:19.058029
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '77a8cbdb6a08'
down_revision: str | None = 'c9b584045ca2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tournament_stages_league_name', 'tournament_stages', ['league_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tournament_stages_league_name', 'tournament_stages', type_='unique')
    # ### end Alembic commands ###
