"""series format and is_conditional_game are nullable until phase 2

Revision ID: c25b0299e248
Revises: ec3ee10dcfcb
Create Date: 2026-08-27 04:10:57.904421
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c25b0299e248'
down_revision: str | None = 'ec3ee10dcfcb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'is_conditional_game',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('series', 'format',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Going back to NOT NULL fails on any row that legitimately has no value yet, so the
    # unknowns are collapsed onto a default first. This direction is lossy by nature: it
    # cannot tell an unknown format from a real bo3.
    op.execute("update series set format = 'bo3' where format is null")
    op.execute("update matches set is_conditional_game = false where is_conditional_game is null")
    op.alter_column('series', 'format',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('matches', 'is_conditional_game',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
