"""league mapping history

Revision ID: c9b584045ca2
Revises: 168ea133f356
Create Date: 2026-08-27 05:03:01.816768
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c9b584045ca2'
down_revision: str | None = '168ea133f356'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('liquipedia_slug', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('is_lan', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name=op.f('fk_league_mappings_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_mappings'))
    )
    op.create_index('ix_league_mappings_active', 'league_mappings', ['league_id', 'superseded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_league_mappings_active', table_name='league_mappings')
    op.drop_table('league_mappings')
    # ### end Alembic commands ###
