"""live snapshots: nullable server_steam_id, add source

Revision ID: ec3ee10dcfcb
Revises: 6c1b498f1c83
Create Date: 2026-08-26 13:08:29.826238
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ec3ee10dcfcb'
down_revision: str | None = '6c1b498f1c83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: without it this fails the moment the table
    # has rows. Autogenerate cannot know that, hence the "please adjust" banner above.
    op.add_column(
        'raw_live_snapshots',
        sa.Column(
            'source',
            sa.String(length=32),
            nullable=False,
            server_default='live_league_games',
        ),
    )
    op.alter_column('raw_live_snapshots', 'server_steam_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_live_snapshots', 'server_steam_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('raw_live_snapshots', 'source')
    # ### end Alembic commands ###
